ZPS-7117: fix for changes in MySQLdb 1.2.5
Upon upgrading zenoss-py-deps from MySQL-python 1.2.3 to 1.2.5 (a.k.a.
MySQLdb), we started seeing the following errors in zenmapper.

    Traceback (most recent call last):
      File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/zenmapper.py", line 220, in update_nodes
        added = connections.update_node(node, force=self.options.force)
      File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/connections.py", line 44, in wrapper
        return f(*args, **kwargs)
      File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/connections.py", line 133, in update_node
        provider.load()
      File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/graph.py", line 481, in load
        self.uuid)
      File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/graph.py", line 692, in execute
        return self.with_retry("execute", statement, params)
      File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/graph.py", line 730, in with_retry
        getattr(cursor, fn_name)(*args, **kwargs)
      File "/opt/zenoss/lib/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
        query = query % tuple([db.literal(item) for item in args])
    TypeError: not all arguments converted during string formatting

The MySQLdb change is in the following commit, and it appears that some
other people have also experienced the regression.

https://github.com/farcepest/MySQLdb1/commit/87d1145c0d6ee4f5a8ecf6d5c62d2479b9cf27ea

The problem occurs because MySQLdb's execute is now expecting args to be
a sequence rather than implicitely treating a single value as a sequence
of length 1.

This change causes us to always send args as a sequence.